<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Volo.Docs.HttpApi</AssemblyName>
    <PackageId>Volo.Docs.HttpApi</PackageId>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Volo.Docs.Application.Contracts\Volo.Docs.Application.Contracts.csproj" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc" Version="9.3.0-rc.1" />
  </ItemGroup>
</Project>