<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Volo.Docs.EntityFrameworkCore</AssemblyName>
    <PackageId>Volo.Docs.EntityFrameworkCore</PackageId>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Volo\Docs\NewFolder\**" />
    <EmbeddedResource Remove="Volo\Docs\NewFolder\**" />
    <None Remove="Volo\Docs\NewFolder\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Volo.Docs.Domain\Volo.Docs.Domain.csproj" />
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="9.3.0-rc.1" />
  </ItemGroup>
</Project>