<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Volo.Abp.Users.EntityFrameworkCore</AssemblyName>
    <PackageId>Volo.Abp.Users.EntityFrameworkCore</PackageId>
    <AssetTargetFallback>$(AssetTargetFallback);portable-net45+win8+wp8+wpa81;</AssetTargetFallback>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.EntityFrameworkCore" Version="9.3.0-rc.1" />
    <ProjectReference Include="..\Volo.Abp.Users.Domain\Volo.Abp.Users.Domain.csproj" />
  </ItemGroup>
</Project>