<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0</TargetFrameworks>
    <RootNamespace />
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Validation" Version="9.3.0-rc.1" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenIddict.Abstractions" Version="6.4.0" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.5" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Volo\Abp\OpenIddict\Localization\OpenIddict\*.json" />
    <Content Remove="Volo\Abp\OpenIddict\Localization\OpenIddict\*.json" />
  </ItemGroup>
</Project>