<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Volo.ClientSimulation</AssemblyName>
    <PackageId>Volo.ClientSimulation</PackageId>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Http.Client.IdentityModel" Version="9.3.0-rc.1" />
  </ItemGroup>
</Project>