<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="IdentityModel" Version="7.0.0" />
    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.Contracts" Version="9.3.0-rc.1" />
  </ItemGroup>
</Project>