<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>Volo.Docs.Domain</AssemblyName>
    <PackageId>Volo.Docs.Domain</PackageId>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Volo\Docs\Localization\Domain\*.json" />
    <Content Remove="Volo\Docs\Localization\Domain\*.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.5" />
    <PackageReference Include="Octokit" Version="14.0.0" />
    <PackageReference Include="NEST" Version="7.17.5" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="9.0.5" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.2.0" />
    <PackageReference Include="itext7" Version="9.2.0" />
    <PackageReference Include="itext7.pdfhtml" Version="6.2.0" />
    <PackageReference Include="Markdig.Signed" Version="0.41.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Volo.Docs.Domain.Shared\Volo.Docs.Domain.Shared.csproj" />
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="9.3.0-rc.1" />
    <PackageReference Include="Volo.Abp.Caching" Version="9.3.0-rc.1" />
    <PackageReference Include="Volo.Abp.AutoMapper" Version="9.3.0-rc.1" />
    <PackageReference Include="Volo.Abp.BlobStoring" Version="9.3.0-rc.1" />
  </ItemGroup>
</Project>