<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Domain" Version="9.3.0-rc.1" />
    <PackageReference Include="Volo.Abp.Caching" Version="9.3.0-rc.1" />
    <PackageReference Include="Volo.Abp.DistributedLocking.Abstractions" Version="9.3.0-rc.1" />
    <PackageReference Include="Volo.Abp.Identity.Domain" Version="9.3.0-rc.1" />
    <ProjectReference Include="..\Volo.Abp.OpenIddict.Domain.Shared\Volo.Abp.OpenIddict.Domain.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenIddict.Core" Version="6.4.0" />
  </ItemGroup>
</Project>